---
name: lint_and_test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write
  checks: write
  actions: read

jobs:
  shellcheck:
    name: "shellcheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
  lint_and_test:
    name: "Lint and Test"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Do something"
  docker_build:
    name: "Docker build"
    if: |
      github.ref_name == 'main'
    needs:
      - shellcheck
      - lint_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "Do something"
  deploy:
    name: "Deploy to AWS ECS"
    runs-on: ubuntu-latest
    needs:
      - docker_manifest_build
    steps:
      - name: Do something
        run: echo "Do something"
        