---
name: lint_and_test
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write
  checks: write
  actions: read

jobs:
  lint_and_test:
    name: "Lint and Test"
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI/CD Pipeline started - Lint and Test phase"
  docker_build:
    name: "Docker build"
    if: |
      github.ref_name == 'main'
    needs:
      - lint_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: echo "CI/CD Pipeline - Docker build phase for main branch"
  deploy:
    name: "Deploy to AWS ECS"
    runs-on: ubuntu-latest
    needs:
      - docker_build
    steps:
      - name: Deploy
        run: echo "CI/CD Pipeline - Deploy phase completed"
