#!/bin/bash -x


function log () {
  NOW=$(date "+%Y-%m-%d %H:%M:%S%z")
  echo "${NOW} $1"
}

#
# Update Service
#
ls -l
bash .github/workflows/task_definition.sh > task_definition.json
jq < task_definition.json

TASK_DEFINITION_ARN=$(aws ecs register-task-definition --family "camp20250710-definition-family-miyata" \
  --cli-input-json file://task_definition.json \
  | jq -r .taskDefinition.taskDefinitionArn)

if [ -z "${TASK_DEFINITION_ARN}" ]; then
  log "[FAILED] failed to register task definition"
  exit 1
fi

